### PR TITLE
[MGPG-66] fix handling of excluded files

### PR DESCRIPTION
**Pull request by Syquel**
Fixes [MGPG-66](https://issues.apache.org/jira/projects/MGPG/issues/MGPG-66) by adding a check if files match the exclude patterns.

### CODE REVIEW

**Review by elharo — APPROVED** [review]

**Comment by elharo** [comment]
Running through Jenkins 
https://ci-builds.apache.org/job/Maven/job/maven-box/job/maven-gpg-plugin/job/MGPG-66/

**Comment by elharo** [comment]
Many builds failed. might be flaky. Running again.

**Comment by Syquel** [comment]
I was able to reproduce this issue on Linux.

The issue is that `org.codehaus.plexus.util.SelectorUtils#matchPath(java.lang.String, java.lang.String)` does not match the pattern `**/*.asc` on the path `/tmp/maven-gpg-plugin/target/it/sign-release-with-excludes/target/test-1.0-sources.jar.asc`.
On Windows it's working.

I will take a look tomorrow.

**Comment by elharo** [comment]
https://ci-builds.apache.org/job/Maven/job/maven-box/job/maven-gpg-plugin/job/MGPG-66/3/

**Comment by clemensbartz** [comment]
I can confirm this fix is also working on macOS 11.2.3 (Apple Silicon, gpg (GnuPG/MacGPG2) 2.2.24). The test in 4da6921 is successful and was failing before as expected.
Java reports as: `OS name: "mac os x", version: "10.16", arch: "x86_64", family: "mac"`

**Comment by jira-importer** [comment]
Resolve #226

**Comment by jira-importer** [comment]
Resolve #226

**Pull request merged**
