### PR TITLE
[MGPG-130] - Update sigstore extension to ".sigstore.json"

### PR DESCRIPTION
**Pull request by loosebazooka**
Sigstore uses ".sigstore.json" extension in all our plugins, ".sigstore" is no longer used. 

Context: https://github.com/sigstore/sigstore-maven-plugin/blob/main/src/main/java/dev/sigstore/plugin/SigstoreSignAttachedMojo.java#L47

This change is consistent across java clients ([gradle](https://github.com/sigstore/sigstore-java/blob/main/sigstore-gradle/sigstore-gradle-sign-base-plugin/src/main/kotlin/dev/sigstore/sign/SigstoreSignature.kt#L28)) and language clients ([python](https://github.com/sigstore/sigstore-python/blob/53c39d9ff48bee22b0da02e5ef63f23968bc65db/sigstore/_cli.py#L497))

----

Following this checklist to help us incorporate your contribution quickly and easily:

- [x] Make sure there is a [JIRA issue](https://issues.apache.org/jira/browse/MGPG) filed for the change (usually
  before you start working on it). Trivial changes like typos do not require a JIRA issue. Your pull request should
  address just this issue, without pulling in other changes.
- [x] Each commit in the pull request should have a meaningful subject line and body.
- [x] Format the pull request title like `[MGPG-XXX] - Fixes bug in ApproximateQuantiles`, where you replace `MGPG-XXX`
  with the appropriate JIRA issue. Best practice is to use the JIRA issue title in the pull request title and in the
  first line of the commit message.
- [x] Write a pull request description that is detailed enough to understand what the pull request does, how, and why.
- [x] Run `mvn clean verify` to make sure basic checks pass. A more thorough check will be performed on your pull
  request automatically.
- [x] You have run the integration tests successfully (`mvn -Prun-its clean verify`).

If your pull request is about ~20 lines of code you don't need to sign an
[Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf) if you are unsure please ask on the
developers list.

To make clear that you license your contribution under
the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
you have to acknowledge this by using the following check-box.

- [x] I hereby declare this contribution to be licenced under
  the [Apache License Version 2.0, January 2004](http://www.apache.org/licenses/LICENSE-2.0)
- [ ] In any other case, please file
  an [Apache Individual Contributor License Agreement](https://www.apache.org/licenses/icla.pdf).

### CODE REVIEW

**Comment by cstamas** [comment]
I would leave old and add sigstore.json as well

**Comment by loosebazooka** [comment]
> I would leave old and add sigstore.json as well

That works, we just don't intend on making any new signatures using that extension. But I have no strong preference.

**Comment by cstamas** [comment]
Are any of the two maven sigstore plugins alive? Afair, they used ".sigstore" for extension...

**Comment by loosebazooka** [comment]
Both standalone plugin repositories are archived ([1](https://github.com/sigstore/sigstore-maven), [2](https://github.com/sigstore/sigstore-maven-plugin)), things were a little wild west at the beginning :shrug: . The "supported" plugin is integrated into the sigstore-java repository at https://github.com/sigstore/sigstore-java/tree/main/sigstore-maven-plugin. <-- this supersedes the code in https://github.com/sigstore/sigstore-maven-plugin (which is archived). The latest release at https://central.sonatype.com/artifact/dev.sigstore/sigstore-maven-plugin/0.11.0/versions

**Comment by loosebazooka** [comment]
@cstamas updated to re-include ".sigstore". I added a tracker to remove it in 6 months or so (https://github.com/sigstore/sigstore-java/issues/759)

**Comment by loosebazooka** [comment]
This windows test just timing out?

**Comment by loosebazooka** [comment]
@cstamas any chance this could get another look?

**Review by cstamas — APPROVED** [review]

**Comment by jira-importer** [comment]
Resolve #256

**Comment by jira-importer** [comment]
Resolve #256

**Pull request merged**
